---
- name: Install Apache and Ensure it is running
  hosts: all
  become: yes
  become_user: root
  
  tasks:
  
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: Changing apache server's status
    service:
      name: httpd
      state: started
